export const CAROUSEL_SET_LIST = 'CAROUSEL_SET_LIST'
export const CAROUSEL_SET_TOGGLE = 'CAROUSEL_SET_TOGGLE'
export const CAROUSEL_NEXT = 'CAROUSEL_NEXT'
export const CAROUSEL_PREV = 'CAROUSEL_PREV'
